command: [
  "streamlit", 
  "run",
  "app.py",
  "--server.port",
  "8080"
]

env:
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/4b9b953939869799"
  - name: F1_CATALOG
    value: "jai_patel_f1_data"
  - name: F1_SCHEMA
    value: "racing_stats"
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
